name: ci-web
on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-web-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Pin Yarn 4.10.3
        run: corepack prepare yarn@4.10.3 --activate

      - name: Check Yarn
        run: yarn -v  # should display 4.10.3

      - name: Cache Yarn (Berry) artifacts
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn4-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn4-

      - name: Install deps
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: TypeCheck
        run: yarn tsc -b --noEmit

      - name: Build
        run: yarn build
